const CREATE_GAME_SOCKET = 'CREATE_GAME_SOCKET';
const GET_GAME_USERS_SOCKET = 'GET_GAME_USERS_SOCKET';
const GET_CARD_USER_SOCKET = 'GET_CARD_USER_SOCKET';
const DEL_GAME = 'DEL_GAME';
const TURN_SOCKET = 'TURN_SOCKET';
const START_GAME_SOCKET = 'START_GAME_SOCKET';
const ROLL_DICE_SOCKET = 'ROLL_DICE_SOCKET';

module.exports = {
  CREATE_GAME_SOCKET,
  GET_GAME_USERS_SOCKET,
  DEL_GAME,
  GET_CARD_USER_SOCKET,
  TURN_SOCKET,
  START_GAME_SOCKET,
  ROLL_DICE_SOCKET,
};
